### ISSUE TITLE
gpapi-0.3.2: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by blshkv** [NoMore201/googleplay-api#34]
this library is used in GPlayCli and it was working fine with v0.3.1.

However, I'm getting the following error with the latest release (0.3.2):
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/gplaycli", line 11, in <module>
    load_entry_point('GPlayCli==3.15', 'console_scripts', 'gplaycli')()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.5/site-packages/gplaycli/gplaycli.py", line 30, in <module>
    from gpapi.googleplay import GooglePlayAPI
  File "/usr/lib64/python3.5/site-packages/gpapi/googleplay.py", line 14, in <module>
    from . import googleplay_pb2, config, utils
  File "/usr/lib64/python3.5/site-packages/gpapi/googleplay_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

```

Would you have any idea what's wrong?

**Comment by blshkv** [comment]
FYI, it is installed as a system-wide library:
```
/usr/lib64/python3.5/site-packages/gpapi
/usr/lib64/python3.5/site-packages/gpapi-0.3.2-py3.5.egg-info
/usr/lib64/python3.5/site-packages/gpapi-0.3.2-py3.5.egg-info/PKG-INFO
/usr/lib64/python3.5/site-packages/gpapi-0.3.2-py3.5.egg-info/SOURCES.txt
/usr/lib64/python3.5/site-packages/gpapi-0.3.2-py3.5.egg-info/dependency_links.txt
/usr/lib64/python3.5/site-packages/gpapi-0.3.2-py3.5.egg-info/requires.txt
/usr/lib64/python3.5/site-packages/gpapi-0.3.2-py3.5.egg-info/top_level.txt
/usr/lib64/python3.5/site-packages/gpapi/__init__.py
/usr/lib64/python3.5/site-packages/gpapi/__pycache__
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/__init__.cpython-35.opt-1.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/__init__.cpython-35.opt-2.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/__init__.cpython-35.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/config.cpython-35.opt-1.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/config.cpython-35.opt-2.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/config.cpython-35.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/googleplay.cpython-35.opt-1.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/googleplay.cpython-35.opt-2.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/googleplay.cpython-35.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/googleplay_pb2.cpython-35.opt-1.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/googleplay_pb2.cpython-35.opt-2.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/googleplay_pb2.cpython-35.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/utils.cpython-35.opt-1.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/utils.cpython-35.opt-2.pyc
/usr/lib64/python3.5/site-packages/gpapi/__pycache__/utils.cpython-35.pyc
/usr/lib64/python3.5/site-packages/gpapi/config.py
/usr/lib64/python3.5/site-packages/gpapi/device.properties
/usr/lib64/python3.5/site-packages/gpapi/googleplay.py
/usr/lib64/python3.5/site-packages/gpapi/googleplay_pb2.py
/usr/lib64/python3.5/site-packages/gpapi/utils.py
```

**Comment by NoMore201** [comment]
Which version of the protobuf library are you using? How did you install gpapi?
I tried installing it from scratch in a virtualenv, and had no problem so far.

**Comment by blshkv** [comment]
```
dev-libs/protobuf-3.1.0
dev-python/protobuf-python-3.1.0
```

I'm a developer of Pentoo (Gentoo-based) Linux and ported/installed all python tools/libs using standard ```setup.py```  and setuptools.

**Comment by blshkv** [comment]
seems related, I will try 3.5.x

**Comment by blshkv** [comment]
ok, so it works with 3.5.1, thank you for the hint.

Could you specify the required library in the setup.py, something like ```protobuf>=3.5.1```?

P.S. I have not tested 3.2 3.3 3.4 and not sure what would be the minimal requirement.

**Comment by dieterplex** [comment]
Same here w/ protobuf==3.1.0, verified on 3.5.1
